  "
echo -e "  \____/|_| |_| .__/| .__/ \___/ \__\___| |_|    |_|  |_|_|     "
echo -e "              | |   | |                                         "
echo -e "              |_|   |_|                                         "
echo -e " "
echo -e " "
echo -e "Your have Successfully!"
echo -e " "
echo -e "UhppotePHP username is: uhppoteadmin"
echo -e "UhppotePHP password is: uhppotephp"
echo -e " "
echo -e "MySQL username is: root"
echo -e "MySQL password is: ${PASS_MYSQL_ROOT}"
echo -e " "
echo -e "Saved to /var/www/Uhppote-PHP/Passwords_DELETE.txt"
echo -e "${Color_Off}"
